language: php
php:
    - 5.4

services:
  - mysql
script: phpunit --configuration phpunit.xml
matrix:
    allow_failures:
        - php: 5.4
  
notifications:
  email:
    - developers@koomaakiti.com
    
deploy:
  provider: heroku
  api_key:
    secure: "51e225b3-3350-49e9-8f28-46d2e10bf60f"
  appname: local-koomaakiti-com  
  
